root = "."
tmp_dir = "tmp"

[build]
    bin = "./tmp/main"
    cmd = "go build -o ./tmp/main ./cmd/server"
    full_bin = "APP_ENV=dev ./tmp/main"
    include_ext = ["go", "yaml", "yml"]
    exclude_dir = ["tmp", "node_modules"]
    delay = 1000
    stop_on_error = true

